name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@92cf09d451968c28a98482d6c7a0f0e9e1eda946 # v0.2.10
    secrets: inherit
