name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test-monorepo.yml@92cf09d451968c28a98482d6c7a0f0e9e1eda946 # v0.2.10
    secrets: inherit
