name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: ["master"]
  schedule:
    - cron: "18 4 * * 3"

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@92cf09d451968c28a98482d6c7a0f0e9e1eda946 # v0.2.10
    secrets: inherit
