name: Release on tag

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+*

jobs:
  gh-release:
    name: Create release
    permissions:
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/release.yml@92cf09d451968c28a98482d6c7a0f0e9e1eda946 # v0.2.10
    with:
      tag: ${{ github.ref_name }}
      is-monorepo: true
    secrets: inherit
